name: quantumtrade
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  url_launcher: ^6.2.4
  web_socket_channel: ^2.4.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  webview_flutter: ^4.4.2
  permission_handler: ^11.0.1
  flutter_localizations:
    sdk: flutter
  animated_text_kit: ^4.2.2
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

# QuantumTrade için pubspec güncellendi - 3. Commit

  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/
    - assets/icons/

      
       
